//  ----------------------------------------------------------------------------
//  sj_browser_ud
//  ----------------------------------------------------------------------------
/*
    UserDefined placeable event script for VFX Browser to handle incoming events
    generated by matching the listening pattern.
*/
//  ----------------------------------------------------------------------------
/*
    Version 1.00 - 28 Nov 2004 - Sunjammer
    - created
*/
//  ----------------------------------------------------------------------------
#include "sj_browser_i"

void main()
{
    if(GetUserDefinedEventNumber() == SJ_BROWSER_LISTENING_PATTERN)
    {
        // convert and store match
        // NOTE: use module as object cannot identify who spoke aloud
        string sMatch = GetStringUpperCase(GetMatchedSubstring(0));
        SetLocalString(GetModule(), SJ_VAR_BROWSER_MATCH, sMatch);
    }
}
